server:
  port: 8081
  servlet:
    context-path: /practice4
spring:
#  mvc:
#    view:#      prefix: /templates/
#      suffix: .html
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: org.hibernate.dialect.MySQLDialect
    url: jdbc:mysql://localhost:33060/practice
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    # create, create-drop, update, [none]
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false